name: Service Heartbeat

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://portfolio-bot-backend.vercel.app/api/health)
          echo "Response code: $response"
          if [[ "$response" -ne 200 ]]; then
            echo "Service returned non-200 response: $response"
            exit 1
          fi
